#SPDX-License-Identifier: MIT-0
---
# vars file for postgres-master

#for postgres user
db_user: ansible_admin
db_user_password: 1234

#dir for db
logical_data_dir: /pg_data/16
postgres_conf: "{{ logical_data_dir }}/conf.d/01-custom.conf"
pg_hba_conf: "{{ logical_data_dir }}/pg_hba.conf"

#for pgbench
pgbench_pass: 1234
db_name: bench
bench_user: pgbench

# for logging
results_dir: "/tmp/pgbench-results-{{ ansible_date_time.epoch }}"

