#SPDX-License-Identifier: MIT-0
---
# tasks file for minicube

# uncomments, if you need to upgarde system
# - name: Upgrade the OS (apt-get dist-upgrade)
#   ansible.builtin.apt:
#     upgrade: dist

# - name: Update all packages to their latest version
#   ansible.builtin.apt:
#     name: "*"
#     state: latest
#     update_cache: yes


# - import_tasks: minikube-install.yaml 

- import_tasks: conf-main-app.yaml

#- import_tasks: conf-monitoring.yaml