#SPDX-License-Identifier: MIT-0
---
# tasks file for postgres-master

# Installs PostgreSQL 16 + dependencies, prepares /pg_data directory with proper permissions,
# stops default service and cleans existing clusters for manual initialization

# - import_tasks: install.yaml

# - import_tasks: prepare-disk.yaml

# setup postgres, up initdb
# - import_tasks: setup.yaml

#- import_tasks: configure-logging.yaml

# pgbench configuration
#- import_tasks: pgbench.yaml

#  create replicas user and some params
 - import_tasks: replication.yaml
