#SPDX-License-Identifier: MIT-0
---
# tasks file for postgres-master

# Installs PostgreSQL 16 + dependencies, prepares /pg_data directory with proper permissions,
# stops default service and cleans existing clusters for manual initialization

# - import_tasks: install.yaml

# - import_tasks: prepare-disk.yaml

# setup postgre
- import_tasks: setup.yaml

# pgbench configuration
- import_tasks: pgbench.yaml

# replicas
- import_tasks: replication.yaml
