#SPDX-License-Identifier: MIT-0
---
# tasks file for postgres-master

#configuration for install postgre
- import_tasks: install.yaml

#create dir and mount disk
- import_tasks: disk.yaml

# setup postgre
- import_tasks: setup.yaml

# pgbench configuration
- import_tasks: pgbench.yaml

# replicas
- import_tasks: replication.yaml
